version: '2'
services:
    web:
        build: "./dockerfiles/alpine-php"
        container_name: "dietcube_sample_app"
        working_dir: "/app"
        ports:
            - "$APP_PORT:$APP_PORT"
        volumes:
            - "./:/app"
        command: sh -c "DIET_ENV=$DIET_ENV php -d variables_order=EGPCS -S 0:$APP_PORT -t webroot/"
