version: "2"
services:
    web:
        build: dockerfiles/alpine-php
        ports:
            - $APP_PORT:$APP_PORT
        volumes:
            - ./:/app
        working_dir: /app
        command: composer install
